steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/watermark', '.' ]
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/watermark']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'watermark', '--image', 'gcr.io/$PROJECT_ID/watermark', '--region', 'us-central1']
images:
- 'gcr.io/$PROJECT_ID/watermark'
